// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhishGuard.Data;

#nullable disable

namespace PhishGuard.Migrations
{
    [DbContext(typeof(PhishGuardContext))]
    [Migration("20260324205253_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PhishGuard.Models.DailyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MetricId"));

                    b.Property<decimal?>("CompanySecurityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly>("MetricDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalBlocked")
                        .HasColumnType("int");

                    b.Property<int>("TotalConfirmedPhishing")
                        .HasColumnType("int");

                    b.Property<int>("TotalEmailsScanned")
                        .HasColumnType("int");

                    b.Property<int>("TotalEmployeeReports")
                        .HasColumnType("int");

                    b.Property<int>("TotalSafe")
                        .HasColumnType("int");

                    b.Property<int>("TotalSimulationsCaught")
                        .HasColumnType("int");

                    b.Property<int>("TotalSimulationsSent")
                        .HasColumnType("int");

                    b.Property<int>("TotalUrlsBlocked")
                        .HasColumnType("int");

                    b.Property<int>("TotalUrlsChecked")
                        .HasColumnType("int");

                    b.Property<int>("TotalWarnings")
                        .HasColumnType("int");

                    b.HasKey("MetricId");

                    b.HasIndex("MetricDate")
                        .IsUnique();

                    b.ToTable("DailyMetrics");
                });

            modelBuilder.Entity("PhishGuard.Models.Email", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmailId"));

                    b.Property<string>("BodyPreview")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Classification")
                        .HasColumnType("int");

                    b.Property<bool>("IsReported")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SenderDisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("EmailId");

                    b.HasIndex("Classification");

                    b.HasIndex("OverallScore");

                    b.HasIndex("RecipientId", "ReceivedAt");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("PhishGuard.Models.EmailScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<int>("EmailId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("ScoreId");

                    b.HasIndex("EmailId", "Dimension");

                    b.ToTable("EmailScores");
                });

            modelBuilder.Entity("PhishGuard.Models.EmailUrl", b =>
                {
                    b.Property<int>("UrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UrlId"));

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("DomainAgeDays")
                        .HasColumnType("int");

                    b.Property<int>("EmailId")
                        .HasColumnType("int");

                    b.Property<string>("FinalUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool?>("IsSafe")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("SafeBrowsingResult")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UrlId");

                    b.HasIndex("Domain");

                    b.HasIndex("EmailId");

                    b.ToTable("EmailUrls");
                });

            modelBuilder.Entity("PhishGuard.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PhishGuard.Models.EmployeeTraining", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<int>("BestStreak")
                        .HasColumnType("int");

                    b.Property<int>("CurrentDifficulty")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DifficultyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSimulationAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ScorePoints")
                        .HasColumnType("int");

                    b.Property<int>("TotalClicked")
                        .HasColumnType("int");

                    b.Property<int>("TotalCorrectlyReported")
                        .HasColumnType("int");

                    b.Property<int>("TotalIgnored")
                        .HasColumnType("int");

                    b.Property<int>("TotalSimulationsReceived")
                        .HasColumnType("int");

                    b.HasKey("TrainingId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeTrainings");
                });

            modelBuilder.Entity("PhishGuard.Models.PhishingCampaign", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CampaignId"));

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhishingIndicators")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TemplateBody")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TemplateSender")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TemplateSubject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("PhishingCampaigns");
                });

            modelBuilder.Entity("PhishGuard.Models.PhishingReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmailId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsConfirmedPhishing")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReportReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("EmailId");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("PhishingReports");
                });

            modelBuilder.Entity("PhishGuard.Models.ScoringRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Pattern")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RuleDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ScoreValue")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("RuleId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("ScoringRules");

                    b.HasData(
                        new
                        {
                            RuleId = 1,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 249, DateTimeKind.Utc).AddTicks(9854),
                            Dimension = 0,
                            IsActive = true,
                            RuleDescription = "Domain found in threat intelligence feeds",
                            RuleName = "Known phishing domain",
                            ScoreValue = 90m
                        },
                        new
                        {
                            RuleId = 2,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(408),
                            Dimension = 0,
                            IsActive = true,
                            RuleDescription = "Exact URL found in threat feeds",
                            RuleName = "Known phishing URL",
                            ScoreValue = 95m
                        },
                        new
                        {
                            RuleId = 3,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(410),
                            Dimension = 0,
                            IsActive = true,
                            RuleDescription = "Sender email in threat database",
                            RuleName = "Known phishing sender",
                            ScoreValue = 85m
                        },
                        new
                        {
                            RuleId = 4,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(411),
                            Dimension = 1,
                            IsActive = true,
                            RuleDescription = "Sender domain registered less than 30 days ago",
                            RuleName = "New domain (< 30 days)",
                            ScoreValue = 40m
                        },
                        new
                        {
                            RuleId = 5,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(412),
                            Dimension = 1,
                            IsActive = true,
                            RuleDescription = "Sender domain registered less than 7 days ago",
                            RuleName = "Very new domain (< 7 days)",
                            ScoreValue = 70m
                        },
                        new
                        {
                            RuleId = 6,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(413),
                            Dimension = 1,
                            IsActive = true,
                            RuleDescription = "Domain similar to a known legitimate domain",
                            RuleName = "Lookalike domain",
                            ScoreValue = 60m
                        },
                        new
                        {
                            RuleId = 7,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(414),
                            Dimension = 2,
                            IsActive = true,
                            Pattern = "act now|immediate action|expires today|last chance|urgent",
                            RuleDescription = "Email contains artificial urgency",
                            RuleName = "Urgency language",
                            ScoreValue = 25m
                        },
                        new
                        {
                            RuleId = 8,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(488),
                            Dimension = 2,
                            IsActive = true,
                            Pattern = "CEO|director|executive|management requires",
                            RuleDescription = "Email impersonates authority figure",
                            RuleName = "Authority manipulation",
                            ScoreValue = 30m
                        },
                        new
                        {
                            RuleId = 9,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(489),
                            Dimension = 2,
                            IsActive = true,
                            Pattern = "account suspended|security breach|unauthorized access|locked out",
                            RuleDescription = "Email uses fear to prompt action",
                            RuleName = "Fear tactics",
                            ScoreValue = 35m
                        },
                        new
                        {
                            RuleId = 10,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(490),
                            Dimension = 2,
                            IsActive = true,
                            Pattern = "you've won|congratulations|free gift|claim your prize",
                            RuleDescription = "Email promises unrealistic rewards",
                            RuleName = "Too-good-to-be-true",
                            ScoreValue = 45m
                        },
                        new
                        {
                            RuleId = 11,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(491),
                            Dimension = 2,
                            IsActive = true,
                            Pattern = "verify your account|confirm your password|update your information|click here to log in",
                            RuleDescription = "Email requests sensitive information",
                            RuleName = "Credential request",
                            ScoreValue = 50m
                        },
                        new
                        {
                            RuleId = 12,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(492),
                            Dimension = 3,
                            IsActive = true,
                            RuleDescription = "Email from internal sender outside business hours",
                            RuleName = "Off-hours email",
                            ScoreValue = 15m
                        },
                        new
                        {
                            RuleId = 13,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(493),
                            Dimension = 3,
                            IsActive = true,
                            RuleDescription = "Sender has never emailed this recipient before",
                            RuleName = "First-time sender",
                            ScoreValue = 20m
                        },
                        new
                        {
                            RuleId = 14,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(493),
                            Dimension = 4,
                            IsActive = true,
                            RuleDescription = "Email HTML structure doesn't match known sender templates",
                            RuleName = "Template mismatch",
                            ScoreValue = 35m
                        },
                        new
                        {
                            RuleId = 15,
                            CreatedAt = new DateTime(2026, 3, 24, 20, 52, 53, 250, DateTimeKind.Utc).AddTicks(494),
                            Dimension = 4,
                            IsActive = true,
                            RuleDescription = "Email contains hidden or obfuscated content",
                            RuleName = "Hidden text/links",
                            ScoreValue = 55m
                        });
                });

            modelBuilder.Entity("PhishGuard.Models.SimulationEmail", b =>
                {
                    b.Property<int>("SimulationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SimulationId"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClickedLinkAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TargetEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("SimulationId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("TargetEmployeeId", "Result");

                    b.ToTable("SimulationEmails");
                });

            modelBuilder.Entity("PhishGuard.Models.ThreatIndicator", b =>
                {
                    b.Property<int>("IndicatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IndicatorId"));

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IndicatorId");

                    b.HasIndex("Type", "Value");

                    b.ToTable("ThreatIndicators");
                });

            modelBuilder.Entity("PhishGuard.Models.Email", b =>
                {
                    b.HasOne("PhishGuard.Models.Employee", "Recipient")
                        .WithMany("Emails")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("PhishGuard.Models.EmailScore", b =>
                {
                    b.HasOne("PhishGuard.Models.Email", "Email")
                        .WithMany("Scores")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("PhishGuard.Models.EmailUrl", b =>
                {
                    b.HasOne("PhishGuard.Models.Email", "Email")
                        .WithMany("Urls")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("PhishGuard.Models.EmployeeTraining", b =>
                {
                    b.HasOne("PhishGuard.Models.Employee", "Employee")
                        .WithOne("Training")
                        .HasForeignKey("PhishGuard.Models.EmployeeTraining", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PhishGuard.Models.PhishingCampaign", b =>
                {
                    b.HasOne("PhishGuard.Models.Employee", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("PhishGuard.Models.PhishingReport", b =>
                {
                    b.HasOne("PhishGuard.Models.Email", "Email")
                        .WithMany("Reports")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhishGuard.Models.Employee", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PhishGuard.Models.Employee", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Email");

                    b.Navigation("Reporter");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("PhishGuard.Models.ScoringRule", b =>
                {
                    b.HasOne("PhishGuard.Models.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("PhishGuard.Models.SimulationEmail", b =>
                {
                    b.HasOne("PhishGuard.Models.PhishingCampaign", "Campaign")
                        .WithMany("Simulations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhishGuard.Models.Employee", "TargetEmployee")
                        .WithMany()
                        .HasForeignKey("TargetEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("TargetEmployee");
                });

            modelBuilder.Entity("PhishGuard.Models.Email", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Scores");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("PhishGuard.Models.Employee", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("PhishGuard.Models.PhishingCampaign", b =>
                {
                    b.Navigation("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
